basedir: /

# html lang
language: "it"

# main menu navigation
menu:
  welcome: welcome
  talks_speakers: talk & speaker
  schedule: programma
  # scommentare per generare pagina
  # menu item for workshop
  workshop: workshop
  sponsor: sponsor

# workshops submenu (comment out if only one workshop: add items for multiple workshops)
workshop_submenu:
  RabbitMQ: Gentle introduction to RabbitMQ
  introduzione_kubernetes: Introduzione a Kubernetes
  tanzu: Tanzu Application Platform

# welcome submenu
welcome_submenu:
#  cfp: call for paper
  about: about
  coc: codice di condotta
  scholarships: borse di studio
  where: dove e come
  # delete this row to take out of the menu


# stylesheets loaded in the <head>
stylesheets:
- /assets/css/global.css

# scripts loaded in the end of the body / commented out to prevent errors in compiling layout.pug
scripts:
- /assets/js/menu.js
